/**
 * `bot:investigate` scoped command (FR-033). Posts a structured
 * root-cause analysis on an issue, idempotent across re-triggers via
 * the marker `<!-- bot:investigate:<issue_number> -->`. Stateless
 * one-shot: no `ship_intents` row, no PR creation, no label mutation.
 *
 * The analysis is generated by a single Bedrock call; the prompt
 * declines to invent context when the issue has empty body and no
 * comments (per FR-017: surface insufficient context honestly).
 */

import type { Octokit } from "octokit";
import type { Logger } from "pino";

import { logger as rootLogger } from "../../../logger";
import { buildScopedMarker, upsertMarkerComment } from "./marker-comment";

const SCOPED_MARKER_VERB = "investigate";

export const INVESTIGATE_SYSTEM_PROMPT = `You produce a root-cause analysis for a GitHub issue.
The reader is a maintainer deciding whether to invest engineering time on this issue.
Return Markdown with these sections in order:
  ### Root-cause hypothesis
  ### Files of interest
  ### Repro confidence (Low / Medium / High)
  ### Suggested next step
Be honest about insufficient context. If the issue body is empty and no
comments add detail, return: "**Insufficient context**: the issue lacks
a description, repro steps, and supporting comments. Ask the reporter
for more detail before investing in this issue."`;

export interface RunInvestigateInput {
  readonly octokit: Pick<Octokit, "rest" | "paginate">;
  readonly owner: string;
  readonly repo: string;
  readonly issue_number: number;
  readonly callLlm: (input: { systemPrompt: string; userPrompt: string }) => Promise<string>;
  readonly log?: Logger;
}

export async function runInvestigate(input: RunInvestigateInput): Promise<{ comment_id: number }> {
  const log = (input.log ?? rootLogger).child({
    event: "ship.scoped.investigate",
    owner: input.owner,
    repo: input.repo,
    issue_number: input.issue_number,
  });

  const issue = await input.octokit.rest.issues.get({
    owner: input.owner,
    repo: input.repo,
    issue_number: input.issue_number,
  });

  // Skip our own marker comments to avoid feeding prior bot output back
  // into the classifier on re-trigger.
  const ourPriorMarker = buildScopedMarker({
    verb: SCOPED_MARKER_VERB,
    number: input.issue_number,
  });

  // Paginate through all comment pages: a bare `listComments` capped at
  // 100/page would silently truncate context on issues with extensive
  // discussion. The classifier then runs on a half-snapshot.
  const allCommentRows = await input.octokit.paginate(input.octokit.rest.issues.listComments, {
    owner: input.owner,
    repo: input.repo,
    issue_number: input.issue_number,
    per_page: 100,
  });

  const comments = allCommentRows
    .filter((c) => !(c.body ?? "").includes(ourPriorMarker))
    .map((c) => ({ author: c.user?.login ?? "(unknown)", body: c.body ?? "" }));

  const userPrompt = [
    `Title: ${issue.data.title}`,
    `Body:\n${issue.data.body ?? "(empty)"}`,
    `Comments (${comments.length}):`,
    ...comments.map((c) => `  @${c.author}: ${c.body.slice(0, 600)}`),
  ].join("\n");

  const analysis = await input.callLlm({
    systemPrompt: INVESTIGATE_SYSTEM_PROMPT,
    userPrompt,
  });

  const marker = ourPriorMarker;
  const body = `${analysis.trim()}\n\n${marker}`;

  const comment_id = await upsertMarkerComment({
    octokit: input.octokit,
    owner: input.owner,
    repo: input.repo,
    issue_number: input.issue_number,
    marker,
    body,
    source: "agent",
    log,
  });

  log.info({ comment_id }, "ship.scoped.investigate posted");
  return { comment_id };
}
