/**
 * `bot:summarize` scoped command (FR-031). Posts a structured PR
 * change-summary comment, idempotent across re-triggers via the marker
 * `<!-- bot:summarize:<pr_number> -->`. Stateless one-shot — no
 * `ship_intents` row, no tracking comment, no thread resolution.
 *
 * The summary is generated by a single Bedrock call; the prompt is
 * deliberately compact (cost-bounded, FR-016 observability) and
 * declines to invent details when the PR diff is empty.
 *
 * Closed PRs still receive a summary, with a leading line marking the
 * PR as closed (read-only operation).
 */

import type { Octokit } from "octokit";
import type { Logger } from "pino";

import { logger as rootLogger } from "../../../logger";
import { buildScopedMarker, upsertMarkerComment } from "./marker-comment";

const SCOPED_MARKER_VERB = "summarize";

export const SUMMARIZE_SYSTEM_PROMPT = `You generate a concise change-summary for a GitHub pull request.
The reader is a maintainer scanning the PR before review.
Return Markdown with these sections in order:
  ### Intent
  ### Notable changes (bulleted)
  ### Risk surface
Do NOT invent details that are not present in the diff or description.
If the diff is empty, return: "_No changes detected; nothing to summarise._"`;

export interface RunSummarizeInput {
  readonly octokit: Pick<Octokit, "rest" | "paginate">;
  readonly owner: string;
  readonly repo: string;
  readonly pr_number: number;
  readonly callLlm: (input: { systemPrompt: string; userPrompt: string }) => Promise<string>;
  readonly log?: Logger;
}

export async function runSummarize(input: RunSummarizeInput): Promise<{ comment_id: number }> {
  const log = (input.log ?? rootLogger).child({
    event: "ship.scoped.summarize",
    owner: input.owner,
    repo: input.repo,
    pr_number: input.pr_number,
  });

  const pr = await input.octokit.rest.pulls.get({
    owner: input.owner,
    repo: input.repo,
    pull_number: input.pr_number,
  });

  const userPrompt = [
    `Title: ${pr.data.title}`,
    `State: ${pr.data.state}${pr.data.merged ? " (merged)" : ""}`,
    `Description:\n${pr.data.body ?? "(no description)"}`,
    `Commits: ${pr.data.commits}, Files changed: ${pr.data.changed_files}, +${pr.data.additions}/-${pr.data.deletions}`,
  ].join("\n\n");

  const summary = await input.callLlm({
    systemPrompt: SUMMARIZE_SYSTEM_PROMPT,
    userPrompt,
  });

  const closedPrefix =
    pr.data.state === "closed"
      ? `> _PR is currently **${pr.data.merged ? "merged" : "closed"}** — summary is read-only._\n\n`
      : "";

  const marker = buildScopedMarker({ verb: SCOPED_MARKER_VERB, number: input.pr_number });
  const body = `${closedPrefix}${summary.trim()}\n\n${marker}`;

  const comment_id = await upsertMarkerComment({
    octokit: input.octokit,
    owner: input.owner,
    repo: input.repo,
    issue_number: input.pr_number,
    marker,
    body,
    source: "agent",
    log,
  });

  log.info({ comment_id }, "ship.scoped.summarize posted");
  return { comment_id };
}
